#!/usr/bin/env bash
urls=(
  "https://dl.getaurora.dev/aurora-stable.iso"
  "https://dl.getaurora.dev/aurora-dx-stable.iso"
  "https://dl.getaurora.dev/aurora-nvidia-open-stable.iso"
  "https://dl.getaurora.dev/aurora-dx-nvidia-open-stable.iso"
  "https://dl.getaurora.dev/aurora-nvidia-stable.iso"
  "https://dl.getaurora.dev/aurora-dx-nvidia-stable.iso"
  "https://dl.getaurora.dev/aurora-hwe-latest.iso"
  "https://dl.getaurora.dev/aurora-dx-hwe-latest.iso"
  "https://dl.getaurora.dev/aurora-hwe-nvidia-open-latest.iso"
  "https://dl.getaurora.dev/aurora-dx-hwe-nvidia-open-latest.iso"
  "https://dl.getaurora.dev/aurora-hwe-nvidia-latest.iso"
  "https://dl.getaurora.dev/aurora-dx-hwe-nvidia-latest.iso"
  "https://download.projectbluefin.io/bluefin-stable.iso"
  "https://download.projectbluefin.io/bluefin-dx-stable.iso"
  "https://download.projectbluefin.io/bluefin-nvidia-stable.iso"
  "https://download.projectbluefin.io/bluefin-dx-nvidia-stable.iso"
  "https://download.bazzite.gg/bazzite-stable.iso"
  "https://download.bazzite.gg/bazzite-nvidia-stable.iso"
  "https://download.bazzite.gg/bazzite-nvidia-open-stable.iso"
  "https://download.bazzite.gg/bazzite-gnome-stable.iso"
  "https://download.bazzite.gg/bazzite-gnome-nvidia-stable.iso"
  "https://download.bazzite.gg/bazzite-gnome-nvidia-open-stable.iso"
  "https://download.bazzite.gg/bazzite-deck-stable.iso"
  "https://download.bazzite.gg/bazzite-deck-gnome-stable.iso"
  "https://download.bazzite.gg/bazzite-ally-stable.iso"
  "https://download.bazzite.gg/bazzite-ally-gnome-stable.iso"
  "https://download.bazzite.gg/bazzite-asus-stable.iso"
  "https://download.bazzite.gg/bazzite-gnome-asus-stable.iso"
  "https://download.bazzite.gg/bazzite-asus-nvidia-stable.iso"
  "https://download.bazzite.gg/bazzite-gnome-asus-nvidia-stable.iso"
  "https://download.bazzite.gg/bazzite-asus-nvidia-open-stable.iso"
  "https://download.bazzite.gg/bazzite-gnome-asus-nvidia-open-stable.iso"
  "https://download.bazzite.gg/bazzite-surface-stable.iso"
  "https://download.bazzite.gg/bazzite-gnome-surface-stable.iso"
  "https://download.bazzite.gg/bazzite-surface-nvidia-open-stable.iso"
  "https://download.bazzite.gg/bazzite-gnome-surface-nvidia-open-stable.iso"
  "https://download.bazzite.gg/bazzite-deck-nvidia-stable.iso"
  "https://download.bazzite.gg/bazzite-deck-nvidia-gnome-stable.iso"
)

for url in "${urls[@]}"; do
  checksum_url="${url}-CHECKSUM"
  checksum=$(curl -L "$checksum_url" 2>/dev/null | awk '{print $1}')
  iso=$(basename "$url")
  echo "$iso $url $checksum"
done